// Generated by CoffeeScript 1.8.0
(function() {
  test("`yieldall` support", function() {
    var x, y;
    x = (function*() {
      var _ref, _result, _send;
      _ref =  (function*() {
        var i, _i;
        for (i = _i = 3; _i <= 4; i = ++_i) {
          (yield i);
        }
      })();
      _result = {};
      while(!_result.done) {
        _result = _ref.next(_send);
        _send = yield _result.value;
      }
    })();
    y = x.next();
    ok(y.value === 3 && !y.done);
    y = x.next(1);
    ok(y.value === 4 && !y.done);
    y = x.next(2);
    arrayEq(y.value, [1, 2]);
    return ok(y.done === true);
  });

}).call(this);
